import React,{useState} from 'react';
import { Link } from 'wouter';
import { Sparkles, Copy, Save, WandSparkles, ArrowLeftRight, Check, Plus } from 'lucide-react';
import { aiPromptLab, savePromptVersion, PromptAction } from '@/services/phase3';
import { useToast } from '@/hooks/use-toast';

const tools:[PromptAction,string,string][]=[['generate','Generator','Describe what you want'],['enhance','Enhancer','Improve an existing prompt'],['fix','Fixer','Find contradictions and gaps'],['translate','Translator','Translate while preserving technical terms'],['variation','Variation','Create multiple alternatives'],['analyze','Analyzer','Score and diagnose a prompt'],['image_to_video','Image → Video','Add motion and temporal direction'],['video_to_image','Video → Image','Extract visual description']];
export default function PromptLab(){
 const {toast}=useToast(); const [tool,setTool]=useState<PromptAction>('generate'); const [text,setText]=useState(''); const [extra,setExtra]=useState(''); const [language,setLanguage]=useState('English'); const [loading,setLoading]=useState(false); const [result,setResult]=useState<any>(null);
 const run=async()=>{if(!text.trim() && tool!=='generate'){toast({title:'Add a prompt first',variant:'destructive'});return}setLoading(true);try{setResult(await aiPromptLab(tool,text,extra,language));}catch(e:any){toast({title:'AI request failed',description:e.message,variant:'destructive'});}finally{setLoading(false)}};
 const primary=Array.isArray(result?.variations)?result.variations:[result?.improvedPrompt||result?.generatedPrompt||result?.enhancedPrompt||result?.prompt||result?.translatedPrompt].filter(Boolean);
 return <main className="min-h-screen bg-[#050609] p-4 pb-28 text-white md:pl-24"><div className="mx-auto max-w-6xl pt-6"><div className="flex items-center gap-3"><Link href="/reels"><a className="rounded-xl bg-white/5 p-2"><ArrowLeftRight className="h-4 w-4"/></a></Link><div><div className="text-xs font-black uppercase tracking-[.2em] text-cyan-300">PromptReels</div><h1 className="text-3xl font-black">AI Prompt Lab</h1></div></div>
 <div className="mt-6 grid gap-4 lg:grid-cols-[250px_1fr]"><aside className="grid grid-cols-2 gap-2 lg:grid-cols-1">{tools.map(([id,name,desc])=><button key={id} onClick={()=>setTool(id)} className={`rounded-2xl border p-4 text-left transition ${tool===id?'border-cyan-300/40 bg-cyan-300/10':'border-white/10 bg-white/[.035]'}`}><div className="flex items-center gap-2 font-black"><WandSparkles className="h-4 w-4 text-cyan-300"/>{name}</div><div className="mt-1 text-xs text-white/40">{desc}</div></button>)}</aside>
 <section className="space-y-4"><div className="rounded-[28px] border border-white/10 bg-white/[.035] p-5"><div className="flex flex-wrap gap-2"><select value={language} onChange={e=>setLanguage(e.target.value)} className="rounded-xl bg-black/40 p-3 text-sm">{['English','Bangla','Hindi','Arabic','Spanish','French','Japanese'].map(x=><option key={x}>{x}</option>)}</select><input value={extra} onChange={e=>setExtra(e.target.value)} placeholder="Extra constraints (optional)" className="min-w-0 flex-1 rounded-xl border border-white/10 bg-black/30 p-3 outline-none"/></div><textarea value={text} onChange={e=>setText(e.target.value)} rows={12} placeholder={tool==='generate'?'Describe the image/video you want…':'Paste your prompt here…'} className="mt-3 w-full rounded-2xl border border-cyan-300/15 bg-black/30 p-4 leading-7 outline-none focus:ring-2 focus:ring-cyan-300/20"/><button onClick={run} disabled={loading} className="mt-3 w-full rounded-xl bg-cyan-400 p-3 font-black text-black disabled:opacity-50">{loading?'Thinking…':'Run AI Tool'}</button></div>
 {result&&<div className="rounded-[28px] border border-cyan-300/15 bg-cyan-300/[.04] p-5"><div className="flex items-center gap-2 font-black text-cyan-200"><Sparkles className="h-4 w-4"/>Result</div>{result.differenceSummary&&<p className="mt-3 text-sm text-white/60">{result.differenceSummary}</p>}{result.issues&&<div className="mt-3 space-y-2">{result.issues.map((x:any,i:number)=><div key={i} className="rounded-xl bg-black/20 p-3 text-sm"><b>{x.problem||'Issue'}</b><div className="text-white/50">{x.why||x.fix||''}</div></div>)}</div>}<div className="mt-4 grid gap-3">{primary.map((p:string,i:number)=><div key={i} className="rounded-2xl border border-white/10 bg-black/25 p-4"><div className="mb-2 text-xs font-black text-cyan-300">{Array.isArray(result.variations)?`Variation ${i+1}`:'Generated Prompt'}</div><p className="whitespace-pre-wrap text-sm leading-6">{p}</p><div className="mt-3 flex gap-2"><button onClick={()=>navigator.clipboard.writeText(p)} className="rounded-lg bg-white/10 px-3 py-2 text-xs font-bold"><Copy className="mr-1 inline h-3 w-3"/>Copy</button><button onClick={async()=>{try{await savePromptVersion({promptText:p,source:tool==='variation'?'AI Variation':tool==='enhance'?'AI Enhanced':'Original'});toast({title:'Version saved'})}catch(e:any){toast({title:'Could not save',description:e.message,variant:'destructive'})}}} className="rounded-lg bg-white/10 px-3 py-2 text-xs font-bold"><Save className="mr-1 inline h-3 w-3"/>Save Version</button></div></div>)}</div>{result.negativePrompt&&<div className="mt-4 rounded-xl bg-black/20 p-3 text-sm"><b>Negative prompt</b><p className="mt-1 text-white/60">{result.negativePrompt}</p></div>}</div>}
 </section></div></div></main>
}
